---
title: "analysis-recipient effects"
author: "Ye Dam Yi"
date: "4/8/2021"
output: html_document
---
#### Load library
```{r libraries}
library(tidyverse)
library(labelled)
library(rstatix)
library(haven)
library(knitr)
```

#### Read in data
```{r import-data}
risk_excluded <- read_sav("data/risk_excluded.sav")

# check data
glimpse(risk_excluded)

risk_excluded <- read_spss("data/risk_excluded.sav")

# convert types
# risk_excluded <- risk_excluded %>% 
#   mutate_if(is.labelled, labelled::to_factor)

# convert type
risk_excluded <- risk_excluded %>% 
  mutate(gender = as_factor(gender),
         condition = as_factor(condition),
         rel_self = as_factor(rel_self),
         rel_friend1 = as_factor(rel_friend1),
         rel_friend2 = as_factor(rel_friend2)) 

# write_sav(risk_excluded, "data/risk_excluded.sav")

# check data
glimpse(risk_excluded)
```


#### Effects of recipient on each of the outcome variables
```{r missing-data}

summary(risk_excluded)
risk_excluded %>% summarise_all(~ sum(is.na(.)))

```
```{r recode}
risk_excluded <- risk_excluded %>% 
  mutate(risklevel = case_when(risklevel == 0 ~ 1,
                               risklevel == 1 ~ 2,
                               risklevel == 2 ~ 3,
                               risklevel == 3 ~ 4,
                               risklevel == 4 ~ 5,
                               risklevel == 5 ~ 6,
                               risklevel == 6 ~7),
         neg = case_when(neg == 0 ~ 1,
                         neg == 1 ~ 2,
                         neg == 2 ~ 3,
                         neg == 3 ~ 4,
                         neg == 4 ~ 5),
         pos = case_when(pos == 0 ~ 1,
                         pos == 1 ~ 2,
                         pos == 2 ~ 3,
                         pos == 3 ~ 4,
                         pos == 4 ~ 5),
         alert = case_when(alert == 0 ~ 1,
                         alert == 1 ~ 2,
                         alert == 2 ~ 3,
                         alert == 3 ~ 4,
                         alert == 4 ~ 5),
         riskyrisk = case_when(riskyrisk == 0 ~ 1,
                         riskyrisk == 1 ~ 2,
                         riskyrisk == 2 ~ 3,
                         riskyrisk == 3 ~ 4,
                         riskyrisk == 4 ~ 5),
         riskavrisk = case_when(riskavrisk == 0 ~ 1,
                         riskavrisk == 1 ~ 2,
                         riskavrisk == 2 ~ 3,
                         riskavrisk == 3 ~ 4,
                         riskavrisk == 4 ~ 5))

```


```{r recipient-effects}
# risk taking
risk_excluded %>% 
  ggplot(aes(y = risklevel, x = condition)) +
  geom_boxplot()

# numbers
risk_excluded %>% group_by(condition) %>% 
  get_summary_stats(risklevel, type = "mean_sd")

# t-test
risk_excluded %>% 
  t_test(risklevel ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 



# negative emotions
risk_excluded %>% 
  ggplot(aes(y = neg, x = condition)) +
  geom_boxplot()

# numbers
risk_excluded %>% group_by(condition) %>% 
  get_summary_stats(neg, type = "mean_sd")
# t-test
risk_excluded %>% 
  t_test(neg ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

# positive emotions
risk_excluded %>% 
  ggplot(aes(y = pos, x = condition)) +
  geom_boxplot()
# numbers
risk_excluded %>% group_by(condition) %>% 
  get_summary_stats(pos, type = "mean_sd")
# t-test
risk_excluded %>% 
  t_test(pos ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 



# alertness
risk_excluded %>% 
  ggplot(aes(y = alert, x = condition)) +
  geom_boxplot()
# numbers
risk_excluded %>% group_by(condition) %>% 
  get_summary_stats(alert, type = "mean_sd")
# t-test
risk_excluded %>% 
  t_test(alert ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 


```


