---
title: "multigroup analysis"
author: "Ye Dam Yi"
date: "4/24/2021"
output: html_document
---

```{r setup, include=FALSE}
require(lavaan)
require(tidyverse)
require(haven)
require(rstatix)
```


### 1. Pairwise contrasts based on groups
```{r read-data}
single <- read_spss("data/single.sav")
relationship <- read_spss("data/inrelationship.sav")

single <- single %>% 
  mutate(gender = as_factor(gender),
         condition = as_factor(condition),
         rel_self = as_factor(rel_self),
         rel_friend1 = as_factor(rel_friend1),
         rel_friend2 = as_factor(rel_friend2)) 

single <- single %>% 
  mutate(risklevel = case_when(risklevel == 0 ~ 1,
                               risklevel == 1 ~ 2,
                               risklevel == 2 ~ 3,
                               risklevel == 3 ~ 4,
                               risklevel == 4 ~ 5,
                               risklevel == 5 ~ 6,
                               risklevel == 6 ~7),
         neg = case_when(neg == 0 ~ 1,
                         neg == 1 ~ 2,
                         neg == 2 ~ 3,
                         neg == 3 ~ 4,
                         neg == 4 ~ 5),
         pos = case_when(pos == 0 ~ 1,
                         pos == 1 ~ 2,
                         pos == 2 ~ 3,
                         pos == 3 ~ 4,
                         pos == 4 ~ 5),
         alert = case_when(alert == 0 ~ 1,
                         alert == 1 ~ 2,
                         alert == 2 ~ 3,
                         alert == 3 ~ 4,
                         alert == 4 ~ 5),
         riskyrisk = case_when(riskyrisk == 0 ~ 1,
                         riskyrisk == 1 ~ 2,
                         riskyrisk == 2 ~ 3,
                         riskyrisk == 3 ~ 4,
                         riskyrisk == 4 ~ 5),
         riskavrisk = case_when(riskavrisk == 0 ~ 1,
                         riskavrisk == 1 ~ 2,
                         riskavrisk == 2 ~ 3,
                         riskavrisk == 3 ~ 4,
                         riskavrisk == 4 ~ 5))

relationship <- relationship %>% 
  mutate(gender = as_factor(gender),
         condition = as_factor(condition),
         rel_self = as_factor(rel_self),
         rel_friend1 = as_factor(rel_friend1),
         rel_friend2 = as_factor(rel_friend2)) 

relationship <- relationship %>% 
  mutate(risklevel = case_when(risklevel == 0 ~ 1,
                               risklevel == 1 ~ 2,
                               risklevel == 2 ~ 3,
                               risklevel == 3 ~ 4,
                               risklevel == 4 ~ 5,
                               risklevel == 5 ~ 6,
                               risklevel == 6 ~7),
         neg = case_when(neg == 0 ~ 1,
                         neg == 1 ~ 2,
                         neg == 2 ~ 3,
                         neg == 3 ~ 4,
                         neg == 4 ~ 5),
         pos = case_when(pos == 0 ~ 1,
                         pos == 1 ~ 2,
                         pos == 2 ~ 3,
                         pos == 3 ~ 4,
                         pos == 4 ~ 5),
         alert = case_when(alert == 0 ~ 1,
                         alert == 1 ~ 2,
                         alert == 2 ~ 3,
                         alert == 3 ~ 4,
                         alert == 4 ~ 5),
         riskyrisk = case_when(riskyrisk == 0 ~ 1,
                         riskyrisk == 1 ~ 2,
                         riskyrisk == 2 ~ 3,
                         riskyrisk == 3 ~ 4,
                         riskyrisk == 4 ~ 5),
         riskavrisk = case_when(riskavrisk == 0 ~ 1,
                         riskavrisk == 1 ~ 2,
                         riskavrisk == 2 ~ 3,
                         riskavrisk == 3 ~ 4,
                         riskavrisk == 4 ~ 5))

```

```{r summary}
summary(single)
summary(relationship)

# single
single %>% 
  get_summary_stats(riskyrisk, riskavrisk, type = "mean_sd")

single %>% group_by(condition) %>% 
  get_summary_stats(risklevel, type = "mean_sd")

single %>% group_by(condition) %>% 
  get_summary_stats(neg, type = "mean_sd")

single %>% group_by(condition) %>% 
  get_summary_stats(pos, type = "mean_sd")

single %>% group_by(condition) %>% 
  get_summary_stats(alert, type = "mean_sd")

# relationship
relationship %>% 
  get_summary_stats(riskyrisk, riskavrisk, type = "mean_sd")
relationship %>% group_by(condition) %>% 
  get_summary_stats(risklevel, type = "mean_sd")
relationship %>% group_by(condition) %>% 
  get_summary_stats(neg, type = "mean_sd")
relationship %>% group_by(condition) %>% 
  get_summary_stats(pos, type = "mean_sd")
relationship %>% group_by(condition) %>% 
  get_summary_stats(alert, type = "mean_sd")


```
#### Single
```{r tests-single}

# compare means
t.test(single$riskyrisk, single$riskavrisk, paired = TRUE) %>% 
  tidy()

single %>% 
  t_test(risklevel ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

single %>% 
  t_test(neg ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

single %>% 
  t_test(pos ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

single %>% 
  t_test(alert ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

```

#### Relationship
```{r relationship}


# compare means
t.test(relationship$riskyrisk, relationship$riskavrisk, paired = TRUE) %>% 
  tidy()

relationship %>% 
  t_test(risklevel ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

relationship %>% 
  t_test(neg ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

relationship %>% 
  t_test(pos ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

relationship %>% 
  t_test(alert ~ condition, comparisons = list(c("Self", "Surrogate"), c("Self", "Prediction")), paired = FALSE) 

```
