---
title: "relationship prediction"
author: "Ye Dam Yi"
date: "4/24/2021"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(lavaan)
require(haven)
require(QuantPsyc)
require(semTools)
```


```{r data}
pred <- read_spss("data/self_prediction.sav")
glimpse(pred)

```
#### Mediation
```{r mediation}

pred_mediation_free <- '
      # direct effect
    risklevel ~ c(b1a,b1b) * neg + c(b2a,b2b) * pos + c(b3a,b3b) * alert + c(c1,c2) * recipient_num
    # mediator
    neg ~ c(a1a,a1b) * recipient_num
    pos ~ c(a2a,a2b) * recipient_num
    alert ~ c(a3a,a3b) * recipient_num
    # indirect effect c(a*b)
    indirect1_g1 := a1a * b1a
    indirect2_g1 := a2a * b2a
    Indirect3_g1:= a3a * b3a
    indirect1_g2 := a1b * b1b
    indirect2_g2 := a2b * b2b
    Indirect3_g2 := a3b * b3b
    # total effect
    total_g1:= c1 + a1a * b1a + a2a * b2a + a3a * b3a
    total_g2:= c2 + a1b * b1b + a2b * b2b + a3b * b3b
    # covariances
    neg ~~ pos
    pos ~~ alert
    neg ~~ alert
'
pred_fit <- sem(model = pred_mediation_free, data = pred, se = "bootstrap", bootstrap = 5000, group = "group")
summary(pred_fit, fit.measures = TRUE, standardize = TRUE, estimates = TRUE, rsquare = TRUE)

standardizedSolution(pred_fit)
parameterEstimates(pred_fit, boot.ci.type = "bca.simple")

pred_fit_constrained1 <- sem(model = pred_mediation_free, data = pred, se = "bootstrap", bootstrap = 5000, group = "group", group.equal = c("intercepts", "regressions"))
summary(pred_fit_constrained1, fit.measures = TRUE, standardize = TRUE, estimates = TRUE, rsquare = TRUE)


pred_mediation_constrained <- '
    # direct effect
    risklevel ~ b1 * neg + b2 * pos + b3 * alert + c * recipient_num
    # mediator
    neg ~ a1 * recipient_num
    pos ~ a2 * recipient_num
    alert ~ a3 * recipient_num
    # indirect effect (a*b)
    indirect1 := a1 * b1
    indirect2 := a2 * b2
    Indirect3 := a3 * b3
    # total effect
    total := c + (a1 * b1) + (a2 * b2) + (a3 * b3)
    # covariances
    neg ~~ pos
    pos ~~ alert
    neg ~~ alert
'
pred_fit_constrained2 <- sem(model = pred_mediation_constrained, data = pred, se = "bootstrap", bootstrap = 5000, group = "group", group.equal = c("intercepts", "regressions"))

summary(pred_fit_constrained2, fit.measures = TRUE, standardize = TRUE, estimates = TRUE, rsquare = TRUE)
parameterEstimates(pred_fit_constrained2, boot.ci.type = "bca.simple")




# semTools::clipboard(prediction_fit,fit.measures=TRUE,standardized=TRUE, rsquare = TRUE)
# semTools::clipboard(pred_fit_constrained,fit.measures=TRUE,standardized=TRUE, rsquare = TRUE)

anova(pred_fit, pred_fit_constrained1)
anova(pred_fit, pred_fit_constrained2)

```


#### Moderation
```{r moderation}
pred_rel <- pred %>% 
  filter(group == 1)
pred_single <- pred %>% 
  filter(group == 2)

pred_rel_moderation <- lm(riskmc ~ negmc + posmc + alertmc + target + negint + posint + alertint, data = pred_rel)
summary(pred_rel_moderation)
lm.beta(pred_rel_moderation)

pred_single_moderation <- lm(riskmc ~ negmc + posmc + alertmc + target + negint + posint + alertint, data = pred_single)
summary(pred_single_moderation)
lm.beta(pred_single_moderation)
```