---
title: "relationship-final"
author: "Ye Dam Yi"
date: "4/29/2021"
output: html_document
---
```{r setup, include=FALSE}
require(tidyverse)
require(lavaan)
require(haven)
require(QuantPsyc)
```

#### Load data
```{r data}
sur <- read_spss("data/self_surrogate.sav")
pred <- read_spss("data/self_prediction.sav")
glimpse(sur)
glimpse(pred)


```

### Self Surrogate Mediation for Single and Relationship Groups
#### Create data
```{r self-sur-data}
# create data for single
sur_single <- sur %>% 
  filter(group == 2)

# create data for relationship
sur_rel <- sur %>% 
  filter(group == 1)
```

#### Run mediation
```{r self-sur-mediation-single}
sur_single_mediation <- '
    # direct effect
    risklevel ~ b1 * neg + b2 * pos + b3 * alert + c * recipient_num
    # mediator
    neg ~ a1 * recipient_num
    pos ~ a2 * recipient_num
    alert ~ a3 * recipient_num
    # indirect effect (a*b)
    indirect1 := a1 * b1
    indirect2 := a2 * b2
    Indirect3 := a3 * b3
    # total effect
    total := c + (a1 * b1) + (a2 * b2) + (a3 * b3)
    # covariances
    neg ~~ pos
    pos ~~ alert
    neg ~~ alert
'
sur_single_mediation_fit <- sem(model = sur_single_mediation, data = sur_single, se = "bootstrap", bootstrap = 5000)
summary(sur_single_mediation_fit, fit.measures = TRUE, standardize = TRUE, estimates = TRUE, rsquare = TRUE)
standardizedSolution(sur_single_mediation_fit)
parameterEstimates(sur_single_mediation_fit, boot.ci.type = "bca.simple")
```

##### Check results with the ones I have

```{r self-sur-mediation-relationship}

sur_rel_mediation <- '
    # direct effect
    risklevel ~ b1 * neg + b2 * pos + b3 * alert + c * recipient_num
    # mediator
    neg ~ a1 * recipient_num
    pos ~ a2 * recipient_num
    alert ~ a3 * recipient_num
    # indirect effect (a*b)
    indirect1 := a1 * b1
    indirect2 := a2 * b2
    Indirect3 := a3 * b3
    # total effect
    total := c + (a1 * b1) + (a2 * b2) + (a3 * b3)
    # covariances
    neg ~~ pos
    pos ~~ alert
    neg ~~ alert
'
sur_rel_mediation_fit <- sem(model = sur_rel_mediation, data = sur_rel, se = "bootstrap", bootstrap = 5000)
summary(sur_rel_mediation_fit, fit.measures = TRUE, standardize = TRUE, estimates = TRUE, rsquare = TRUE)
parameterEstimates(sur_rel_mediation_fit, boot.ci.type = "bca.simple")
standardizedSolution(sur_rel_mediation_fit)
```


##### Check results with the ones I have



